spring:
  application:
    name: carservice
  devtools:
    remote:
      restart.enable: true

server.port: 0


eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8010/eureka

management:
  endpoints:
    web:
      exposure:
        include: all